# Generated by Django 3.2.12 on 2022-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=5)),
                ('contact', models.CharField(max_length=10)),
                ('standard', models.IntegerField(max_length=2)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
